services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
      POSTGRES_DB: ragdb
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  milvus:
    image: milvusdb/milvus:v2.4.9
    container_name: milvus
    environment:
      ETCD_USE_EMBED: "true"
      MINIO_USE_EMBED: "true"
      MILVUS_LOG_LEVEL: info
    command: ["milvus", "run", "standalone"]
    volumes:
      - ./milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
    restart: unless-stopped