version: '3.8'
services:
  rdb:
    image: postgres:15.3-alpine
    container_name: postgresql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    restart: always

  vectordb:
    image: milvusdb/milvus:latest
    container_name: milvus_db
    environment:
  <tên_dịch_vụ_2>:
    build: . # Xây dựng từ Dockerfile trong thư mục hiện tại
    ...