version: '3.8'

services:
  # Container 1: PostgreSQL Database (RDB)
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - rag_network

  # Container 2: Milvus Vector Database (with embedded dependencies)
  milvus:
    image: milvusdb/milvus:v2.3.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_USE_EMBED: true
      ETCD_DATA_DIR: /var/lib/milvus/etcd
      COMMON_STORAGETYPE: local
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus
    networks:
      - rag_network

  # Container 3: RAG API Service (auto-processes PDFs on startup)
  rag:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - milvus
    volumes:
      - ./data:/app/data
    networks:
      - rag_network

volumes:
  postgres_data:
  milvus_data:

networks:
  rag_network:
    driver: bridge